yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -10,6 +10,10 @@ jobs:
   build:
     runs-on: ubuntu-latest
 
+    strategy:
+      matrix:
+        python-version: [3.9, 3.11, 3.12]  
+
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
@@ -17,18 +21,36 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
-        python-version: '3.12'
+        python-version: ${{ matrix.python-version }}
 
     - name: Install pipenv
       run: python -m pip install --upgrade pip pipenv
+
+    - name: Verify Pipfile exists
+      run: |
+        if [ -f "$GITHUB_WORKSPACE/Pipfile" ]; then
+          echo "Pipfile found at $GITHUB_WORKSPACE."
+        else
+          echo "Pipfile NOT found at $GITHUB_WORKSPACE."
+          exit 1
+        fi
 
     - name: Set PIPENV_PIPFILE environment variable
       run: echo "PIPENV_PIPFILE=$GITHUB_WORKSPACE/Pipfile" >> $GITHUB_ENV
 
     - name: Install dependencies (including dev packages)
+      env:
+        PIPENV_PIPFILE: "$GITHUB_WORKSPACE/Pipfile"
       run: pipenv install --dev --deploy --ignore-pipfile
 
     - name: List Installed Packages
+      env:
+        PIPENV_PIPFILE: "$GITHUB_WORKSPACE/Pipfile"
       run: pipenv run pip list
+
+    - name: Run Tests with pytest
+      env:
+        PIPENV_PIPFILE: "$GITHUB_WORKSPACE/Pipfile"
+      run: pipenv run pytest --maxfail=1 --disable-warnings -v
 
 
